core/urls.py
# django imports occur at runtime, so fail linter
# pylint:disable=import-error
from django.contrib import admin
from django.urls import path, include
# pylint:enable=import-error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls'), name='webapp_urls'),
    path("accounts/", include("allauth.urls")),
]

# Pylint assumes incorrect gloabal var
# pylint:disable=invalid-name
handler404 = 'webapp.views.error_404'
handler403 = 'webapp.views.error_403'
handler500 = 'webapp.views.error_500'
# pylint:enable=invalid-name

webapp/urls.py
""" webapp URL Configuration """
# django imports occur at runtime, so fail linter
# pylint:disable=import-error
from django.urls import path
# pylint:enable=import-error

from . import views

urlpatterns = [
    path('', views.CardList.as_view(), name='home'),
    path('mechs/', views.MechList.as_view(), name='mechs'),
    path('mechs/create/', views.CreateMechView.as_view(), name="mech_create"),
    path(
        'mechs/<slug:slug>/update/',
        views.UpdateMechView.as_view(),
        name="mech_update"
    ),
    path(
        'mechs/<slug:slug>/toggle/',
        views.toggle_mech_status,
        name="mech_toggle"
    ),
    path(
        'mechs/<slug:slug>/delete/',
        views.DeleteMechView.as_view(),
        name="mech_delete"
    ),
    path('mechs/<slug:slug>', views.MechDetail.as_view(), name='mech_detail')
]

webapp/models.py
""" Contains the MVC models for the app """
# django imports occur at runtime, so fail linter
# pylint:disable=import-error
from django.db import models
from django.utils.text import slugify
# pylint:enable=import-error


TECH = ((0, 'Inner Sphere'), (1, 'Clan'), (2, 'Prototype'))
ROLE = (
    (0, 'Ambusher'), (1, 'Brawler'), (2, 'Juggernaut'),
    (3, 'Missle Boat'), (4, 'Scout'), (5, "Skirmisher"),
    (6, 'Sniper'), (7, 'Striker')
)
CLASSIFICATION = ((0, 'Light'), (1, 'Medium'), (2, 'Heavy'), (3, 'Assault'))
WEIGHTS = (
    (0, '20 Ton'), (1, '25 Ton'), (2, '30 Ton'), (3, '35 Ton'),
    (4, '40 Ton'), (5, '45 Ton'), (6, '50 Ton'), (7, '55 Ton'),
    (8, '60 Ton'), (9, '65 Ton'), (10, '70 Ton'), (11, '75 Ton'),
    (12, '80 Ton'), (13, '85 Ton'), (14, '90 Ton'), (15, '95 Ton'),
    (16, '100 Ton')
)
STATUS = ((0, "Not Available"), (1, "Available"))


class Mech(models.Model):
    """
    Stores a single mech entry, image and record_sheet
    fields are used as refernces for urls
    """
    name = models.CharField(max_length=50, unique=True)
    category = models.IntegerField(choices=CLASSIFICATION, default=0)
    weight = models.IntegerField(choices=WEIGHTS, default=0)
    tech_level = models.IntegerField(choices=TECH, default=0)
    role = models.IntegerField(choices=ROLE, default=0)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    record_sheet = models.CharField(max_length=50, default='custom')
    image = models.CharField(max_length=50, default='placeholder')
    battle_value = models.IntegerField(default=9999)
    status = models.IntegerField(choices=STATUS, default=0)

    def save(self, *args, **kwargs):
        """
        Override for model.save to auto generate a slug on edits
        """
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

webapp/forms.py
""" Contains the form definitions for the webapp """
# django imports occur at runtime, so fail linter
# pylint:disable=import-error
from django import forms
# pylint:enable=import-error
from .models import Mech


class CreateMechForm(forms.ModelForm):
    """
    Defines the form used to create a new mech
    """
    class Meta:
        """
        Django defined Class used to define what the form can render
        """
        model = Mech
        fields = [
            'name',
            'category',
            'weight',
            'tech_level',
            'role',
            'description',
            'record_sheet',
            'battle_value',
            'status'
        ]


class UpdateMechForm(forms.ModelForm):
    """
    Defines the form used to edit an existing mech
    """
    class Meta:
        """
        Django defined Class used to define what the form can render
        """
        model = Mech
        fields = [
            'name',
            'category',
            'weight',
            'tech_level',
            'role',
            'description',
            'record_sheet',
            'battle_value',
            'status'
        ]

webapp/views.py
""" Contains the MVC models for the app """
# django imports occur at runtime, so fail linter
# pylint:disable=import-error
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import DeleteView, UpdateView
from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
# pylint:enable=import-error

from .models import Mech
from .forms import CreateMechForm, UpdateMechForm


class CardList(generic.ListView):
    """ Django Class View to list all available mechs by name """
    model = Mech
    queryset = Mech.objects.filter(status=1).order_by('name')
    template_name = 'index.html'
    paginate_by = 10


class MechList(LoginRequiredMixin, generic.ListView):
    """ Django Class View to list all mechs by name """
    login_url = "/accounts/login/"
    model = Mech
    queryset = Mech.objects.all().order_by('name')
    template_name = 'mechs.html'
    paginate_by = 10


class MechDetail(LoginRequiredMixin, generic.ListView):
    """ Django Class View to return information on a given mech """
    login_url = "/accounts/login/"

    def get(self, request, slug, *args, **kwargs):
        """
        Gets all mechs from db
        returns specific mech based on slug
        """
        queryset = Mech.objects.all()
        mech = get_object_or_404(queryset, slug=slug)
        return render(
            request,
            "mech_detail.html",
            {
                "mech": mech
            },
        )


class CreateMechView(PermissionRequiredMixin,
                     LoginRequiredMixin, generic.CreateView):
    """ Django Class View to create a new mech """
    permission_required = "webapp.add_mech"
    login_url = "/accounts/login/"
    model = Mech
    form_class = CreateMechForm
    template_name = 'new_mechs_form.html'
    success_url = reverse_lazy('mechs')

    def form_valid(self, form):
        """ method to display message on form submit """
        messages.success(self.request, "The Mech was successfully created.")
        return super(CreateMechView, self).form_valid(form)


class UpdateMechView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    """ Django Class View to update existing mech """
    permission_required = "webapp.change_mech"
    login_url = "/accounts/login/"
    model = Mech
    form_class = UpdateMechForm
    template_name = 'mechs_form.html'

    def get_success_url(self):
        """ method to direct user to it's details page """
        return reverse('mech_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        """ method to display message on form submit """
        messages.success(self.request, "The Mech was successfully updated.")
        return super(UpdateMechView, self).form_valid(form)


class DeleteMechView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    """ Django Class View to delete an exsisting mech """
    permission_required = "webapp.delete_mech"
    login_url = "/accounts/login/"
    model = Mech
    context_object_name = 'mech'
    success_url = reverse_lazy('mechs')
    template_name = 'mech_delete.html'

    def delete(self, request, *args, **kwargs):
        """ method to display message on delete """
        messages.success(self.request, "The Mech was successfully deleted.")
        return super(DeleteMechView, self).delete(request, *args, **kwargs)


@login_required
@permission_required("webapp.change_mech", raise_exception=True)
def toggle_mech_status(request, slug):
    """ method to change availability of a given mech """
    mech = get_object_or_404(Mech, slug=slug)
    if mech.status == 0:
        mech.status = 1
    else:
        mech.status = 0
    mech.save()
    return redirect('mechs')


def error_404(request, exception):
    """ method to display custom 404 """
    return render(request, '404.html', status=404)


def error_403(request, exception):
    """ method to display custom 403 """
    return render(request, '403.html', status=403)


def error_500(request):
    """ method to display custom 500 """
    return render(request, '500.html', status=500)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    {% load static %}
    <title>Battletech Inventory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Battletech Minature Manager for CI PP4.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>

<body class="d-flex flex-column h-100 main-bg">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Battletech Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{%url 'mechs' %}">Mech Inventory</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if user.is_authenticated %}
                        Welcome, {{ user.get_username }}.
                    {% else %}
                        Account Options
                    {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">Password Change</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'account_reset_password' %}">Password Reset</a>
                    <a class="dropdown-item" href="{% url 'account_signup' %}">Register</a>
                    <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
        </div>
    </nav>
    <div class="container message-container fixed-bottom">
        <div class="row"> 
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="d-flex align-items-center">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Bovine Hero</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
    <script>
        if (document.getElementById('msg') != null) {            
            setTimeout(function () {
                let messages = document.getElementById('msg');
                let alert = new bootstrap.Alert(messages);
                alert.close();
            }, 2000);
        }
    </script>   
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% static "" as baseUrl %}
<div class="container">
    <div class="row">
      <div class="col-12">
        <section id="banner">
            <div id="banner-wrapper">
                <div id="banner-image"></div>
                <div id="banner-cover-text">
                    <h2>Battletech</h2>
                    <h3>Reactor <span class="head-message-1">Online</span><br>
                        Sensors <span class="head-message-2">Online</span><br>
                        Weapons <span class="head-message-3">Online</span>
                    </h3>
                </div>        
            </div>
        </section>
        <section>
            <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-4 text-center">
                    <h4 class="text-center">Board Game</h4>
                    <a href="https://www.catalystgamelabs.com/brands/battletech" target="_blank" rel="noopener" aria-label="Visit Catalyst Games Lab store to purchase board game">
                        <img src="{{ baseUrl }}images/hero/board-game.webp" alt="Board Game Cover" class="img-fluid img-thumbnail">
                    </a>
                    <h5 class="text-center">Board | Game</h5>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4">
                    <h4 class="text-center">Our Battlemechs</h4>
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner text-center">
                            {% for mech in mech_list %}
                                <div class="carousel-item {% if forloop.first %} active {% endif %}">                  
                                    <img src="{{ baseUrl }}images/mechs/{{ mech.image }}-rg.png" alt="{{ mech.name }} slide" class="img-fluid img-thumbnail">
                                    <h5 class="text-center">{{ mech.name }} | {{ mech.get_category_display }} Mech</h5>
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-4 text-center">
                    <h4 class="text-center">Video Game</h4>
                    <a href="https://harebrained-schemes.com/battletech/" target="_blank" rel="noopener" aria-label="Visit Harebrained Schemes store to purchase video game">
                        <img src="{{ baseUrl }}images/hero/game.webp" alt="Video Game Cover" class="img-fluid img-thumbnail">
                    </a>
                    <h5 class="text-center">Video | Game</h5>
                </div>
            </div>
        </section>
      </div>
    </div>
</div>
{% endblock %}

templates/mech_delete.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% static "" as baseUrl %}
<div class="container">
    <div class="row align-items-center">
      <div class="col-sm-6">
        <form method="post">
          {% csrf_token %}
          <h1>Delete Mech</h1>
          <p>Commander, are you sure that you want to delete "{{ mech }}"?</p>
          <p class="form-buttons">
            <input type="submit" class="btn btn-delete" value="Delete">
            <a href="{% url 'mechs'%}" class="btn btn-outline">Cancel</a>
          </p>
        </form>
      </div>
      <div class="image-container text-center col-sm-6" style="padding: 2rem;">
          <img src="{{ baseUrl }}images/mechs/{{ mech.image }}-rg.png" alt="{{ mech.name }} Profile Picture" class="img-fluid img-thumbnail">
      </div>
    </div>
</div>
{%endblock%}

templates/mech_detail.html
{% extends 'base.html' %} {% block content %}

{% load static %}
{% static "" as baseUrl %}
<!-- Fix the toggle and make edit mech finsih on mech view -->
<div class="container">
    <div class="row align-items-center">
        <div class="col-sm-12 col-lg-6 left">            
            <div class="image-container text-center">
                <h2>{{ mech.name }}</h2>
                <img src="{{ baseUrl }}images/mechs/{{ mech.image }}-rg.png" alt="{{ mech.name }} Profile Picture" class="img-fluid img-thumbnail">
                <h5>
                    {{ mech.get_tech_level_display }} | {{ mech.get_category_display }} Mech
                </h5>
                <p>
                    {% if mech.get_status_display == "Available" %}
                        <span class="badge badge-success">{{ mech.get_status_display }}</span>
                    {% else %}
                        <span class="badge badge-warning">{{ mech.get_status_display }}</span>
                    {% endif %}
                </p>
                <p>
                    {% if perms.webapp.change_mech %}
                        <a class="btn btn-warning" href="{% url 'mech_update' mech.slug %}"><i class="fa fa-edit"></i> Edit</a>
                    {% endif %}
                    {% if perms.webapp.delete_mech %}
                        <a class="btn btn-delete" href="{% url 'mech_delete' mech.slug %}"><i class="fa fa-trash"></i> Delete</a>
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="col-12 col-lg-6 text-middle">
            <h3>Unit Summary</h3>
            <p>The {{ mech.name }} is a {{ mech.get_weight_display }}, {{ mech.get_tech_level_display }} Battlemech.</p>
            <p>Typically this mech fulfills as the {{ mech.get_role_display }} in a unit with the base configuration coming in with a BV of: {{ mech.battle_value }}</p> 
            <h4>SARNA: Description</h4>
            <p>{{ mech.description }}</p> 
        </div>
        {% if mech.get_status_display == "Available" %}
    </div>
    <div class="row">
        <div class="col-12 left">
            <div class="text-center iframe-toggle">
                <a class="btn btn-warning" data-toggle="collapse" href="#collapseSheet" role="button" aria-expanded="false" aria-controls="collapseSheet">
                    <i class="fas fa-eye"></i> Examine Record Sheet
                </a>
            </div>
            <div class="collapse" id="collapseSheet">
                <div class="iframe-container text-center">
                    <iframe class="dropdown-item responsive-iframe" src="{{ baseUrl }}images/readouts/{{ mech.record_sheet }}.pdf#view=FitH"></iframe>
                </div>
            </div>
        </div>
        {% endif %}
    </div>


</div>

{% endblock content %}

templates/mechs.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% static "" as baseUrl %}
<div class="container">
    <h1>Battlemechs</h1>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        {% if perms.webapp.change_mech %}
          <p class="lead">Welcome Commander!</p>
          <p><a href="{% url 'mech_create' %}"> Add a New Mech <i class="fas fa-plus-square"></i></a></p>
        {% else %}
          <p class="lead">Welcome Mechwarrior!</p>
        {% endif %}
      </div>
    </div>
    <div class="row">

        <!-- Mech Entries -->
        <div class="col-12">
            <div class="row">
                <table class="table table-sm text-center">
                    <thead>
                      <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Actions</th>
                        <th scope="col">Available</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for mech in mech_list %}
                      <tr>
                        <td>
                          <a href="{% url 'mech_detail' mech.slug  %}">{{ mech.name }}</a>
                        </td>
                        <td>
                          <div class="dropdown show">                 
                            <button class="btn dropdown-toggle btn-block" type="button" id="dropdownMenuButton_{{ mech.slug }}" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fa fa-cogs"></i> Menu
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton_{{ mech.slug }}">
                              <a class="dropdown-item" href="{% url 'mech_detail' mech.slug %}"><i class="fas fa-eye"></i> View Mech</a>
                              {% if mech.get_status_display == "Available" %}
                                <a class="dropdown-item " href="{{ baseUrl }}images/readouts/{{ mech.record_sheet }}.pdf" download><i class="fa fa-download"></i> Download</a>
                              {% endif %}
                              {% if perms.webapp.change_mech %}
                                <a class="dropdown-item" href="{% url 'mech_update' mech.slug %}"><i class="fa fa-edit"></i> Edit</a>
                              {% endif %}
                              {% if perms.webapp.delete_mech %}
                                <a class="dropdown-item" href="{% url 'mech_delete' mech.slug %}"><i class="fa fa-trash"></i> Delete</a>
                              {% endif %}
                            </div>
                          </div>
                        </td>
                        <td>
                          {% if perms.webapp.change_mech %}
                          <a href="{% url 'mech_toggle' mech.slug %}" aria-label="toggle mech availability">
                              {% if mech.get_status_display == "Available" %}
                                <i class="fa fa-toggle-on"></i>
                              {% else %}
                                <i class="fa fa-toggle-off"></i>
                              {% endif %}
                          {% else %}
                            {% if mech.get_status_display == "Available" %}
                              <span class="badge badge-success">{{ mech.get_status_display }}</span>
                            {% else %}
                              <span class="badge badge-warning">{{ mech.get_status_display }}</span>
                            {% endif %}
                          {% endif %}
                          </a>
                        </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>              
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
        {% endif %}
    </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/mechs_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% load static %}
{% static "" as baseUrl %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 left">  
      <h1>Edit Mech</h1>
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <div class="row align-items-center">
      <div class="col-sm-12 col-lg-6 left">            
          <div class="image-container text-center">
              {{ form.name|as_crispy_field }}
                <img src="{{ baseUrl }}images/mechs/{{ mech.image }}-rg.png" alt="{{ mech.name }} Profile Picture" class="img-fluid img-thumbnail">
                {{ form.tech_level|as_crispy_field }}
                {{ form.category|as_crispy_field  }}
                {{ form.status|as_crispy_field }}
          </div>
      </div>
      <div class="col-12 col-lg-6 text-middle">
        {{ form.weight|as_crispy_field }}
        {{ form.role|as_crispy_field }}
        {{ form.battle_value|as_crispy_field }} 
        {{ form.description|as_crispy_field }}
        {{ form.record_sheet|as_crispy_field }} 
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <p class="form-buttons float-right">
          <button style="margin: 1rem;" type="submit" value="Save" class="btn btn-warning">Submit</button>
          <a href="{% url 'mechs'%}" class="btn btn-outline">Cancel</a>
        </p>
      </div>
    </div>
    </form>
</div>
{%endblock%}

templates/new_mechs_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% load static %}
{% static "" as baseUrl %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 left">  
      <h1>Add New Mech</h1>
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <div class="row align-items-center">
      <div class="col-sm-12 col-lg-6 left">            
          <div class="image-container text-center">
              {{ form.name|as_crispy_field }}
                <img src="{{ baseUrl }}images/mechs/placeholder-rg.png" alt="Placeholder Profile Picture" class="img-fluid img-thumbnail">
                {{ form.tech_level|as_crispy_field }}
                {{ form.category|as_crispy_field  }}
                {{ form.status|as_crispy_field }}
          </div>
      </div>
      <div class="col-12 col-lg-6 text-middle">
        {{ form.weight|as_crispy_field }}
        {{ form.role|as_crispy_field }}
        {{ form.battle_value|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        {{ form.record_sheet|as_crispy_field }}
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <p class="form-buttons float-right">
          <button style="margin: 1rem;" type="submit" value="Save" class="btn btn-warning">Submit</button>
          <a href="{% url 'mechs'%}" class="btn btn-outline">Cancel</a>
        </p>
      </div>
    </div>
    </form>
</div>
{%endblock%}